### ISSUE TITLE
500 ERROR

### ISSUE THREAD

**Issue by sujalgoel** [TheBoringDude/magna#11]
https://magna-sc.cf/manga?q=https://manhwatop.com/manga/sweet-home
![image](https://user-images.githubusercontent.com/67121014/121655168-074bc280-cabc-11eb-949d-802752aee7b6.png)

**Comment by tbdsux** [comment]
I am aware of this, it is because of the scraper taking too long on requesting for the website. I am only using the free tier of vercel so once the operation exceeds over **10 seconds** it will error. It is one of the reasons why I am not committing anymore in this repo. 

I am very sorry but this won't be fixed, unless I upgrade to an upper tier service of vercel.

**Comment by sujalgoel** [comment]
you should repl.it then, it's better than vercel!

**Comment by tbdsux** [comment]
i'll try (in the future), but this is it for now,
